'use client';

import React from 'react';
import { FileText, Download, Calendar } from 'lucide-react';

interface ReportGeneratorProps {
  statistics: {
    totalTime: number;
    totalEnergyGenerated: number;
    totalImpacts: number;
    maxSoilCompaction: number;
    avgGeneratorPower: number;
  };
  config: any;
  onGenerateReport: () => void;
}

export default function ReportGenerator({ statistics, config, onGenerateReport }: ReportGeneratorProps) {
  const [isMounted, setIsMounted] = React.useState(false);
  
  React.useEffect(() => {
    setIsMounted(true);
  }, []);
  
  const generatePDFReport = () => {
    const reportContent = `
<!DOCTYPE html>
<html>
<head>
  <title>ADC Simulation Report</title>
  <style>
    body {
      font-family: Arial, sans-serif;
      max-width: 800px;
      margin: 0 auto;
      padding: 20px;
      line-height: 1.6;
    }
    .header {
      text-align: center;
      border-bottom: 2px solid #333;
      padding-bottom: 20px;
      margin-bottom: 30px;
    }
    .section {
      margin-bottom: 30px;
    }
    .section h2 {
      color: #333;
      border-bottom: 1px solid #ccc;
      padding-bottom: 10px;
    }
    .stat-grid {
      display: grid;
      grid-template-columns: repeat(2, 1fr);
      gap: 20px;
      margin: 20px 0;
    }
    .stat-item {
      background: #f5f5f5;
      padding: 15px;
      border-radius: 8px;
    }
    .stat-label {
      font-weight: bold;
      color: #666;
      font-size: 14px;
    }
    .stat-value {
      font-size: 24px;
      color: #333;
      margin-top: 5px;
    }
    .config-table {
      width: 100%;
      border-collapse: collapse;
      margin: 20px 0;
    }
    .config-table th, .config-table td {
      border: 1px solid #ddd;
      padding: 12px;
      text-align: left;
    }
    .config-table th {
      background: #f5f5f5;
    }
    .footer {
      text-align: center;
      margin-top: 40px;
      padding-top: 20px;
      border-top: 1px solid #ccc;
      color: #666;
      font-size: 12px;
    }
  </style>
</head>
<body>
  <div class="header">
    <h1>ADC Simulation Report</h1>
    <p>Artificial Dynamic Compaction Monitoring System</p>
    <p>Generated: ${new Date().toLocaleString()}</p>
  </div>

  <div class="section">
    <h2>Simulation Statistics</h2>
    <div class="stat-grid">
      <div class="stat-item">
        <div class="stat-label">Total Simulation Time</div>
        <div class="stat-value">${statistics.totalTime.toFixed(2)}s</div>
      </div>
      <div class="stat-item">
        <div class="stat-label">Total Energy Generated</div>
        <div class="stat-value">${(statistics.totalEnergyGenerated / 1000).toFixed(2)} kJ</div>
      </div>
      <div class="stat-item">
        <div class="stat-label">Total Impacts</div>
        <div class="stat-value">${statistics.totalImpacts}</div>
      </div>
      <div class="stat-item">
        <div class="stat-label">Max Soil Compaction</div>
        <div class="stat-value">${statistics.maxSoilCompaction.toFixed(1)}%</div>
      </div>
      <div class="stat-item">
        <div class="stat-label">Avg Generator Power</div>
        <div class="stat-value">${statistics.avgGeneratorPower.toFixed(2)} W</div>
      </div>
      <div class="stat-item">
        <div class="stat-label">Final Soil Density</div>
        <div class="stat-value">${(config.initialSoilDensity + statistics.maxSoilCompaction * 4).toFixed(0)} kg/m³</div>
      </div>
    </div>
  </div>

  <div class="section">
    <h2>Configuration Parameters</h2>
    <table class="config-table">
      <tr>
        <th>Parameter</th>
        <th>Value</th>
      </tr>
      <tr>
        <td>Pendulum Mass</td>
        <td>${config.pendulumMass} kg</td>
      </tr>
      <tr>
        <td>Max Height</td>
        <td>${config.maxHeight} m</td>
      </tr>
      <tr>
        <td>Gravity</td>
        <td>${config.gravity} m/s²</td>
      </tr>
      <tr>
        <td>Solar Power</td>
        <td>${config.solarPower} W</td>
      </tr>
      <tr>
        <td>Motor Power</td>
        <td>${config.motorPower} W</td>
      </tr>
      <tr>
        <td>Battery Voltage</td>
        <td>${config.batteryVoltage} V</td>
      </tr>
      <tr>
        <td>Motor Efficiency</td>
        <td>${(config.motorEfficiency * 100).toFixed(1)}%</td>
      </tr>
      <tr>
        <td>Generator Efficiency</td>
        <td>${(config.generatorEfficiency * 100).toFixed(1)}%</td>
      </tr>
    </table>
  </div>

  <div class="footer">
    <p>ADC Simulation System v1.0 | Physics-based Real-time Monitoring</p>
    <p>This report was automatically generated by the ADC Simulation Dashboard</p>
  </div>
</body>
</html>
    `;
    
    const blob = new Blob([reportContent], { type: 'text/html' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `adc_simulation_report_${Date.now()}.html`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
    
    onGenerateReport();
  };
  
  return (
    <div className="bg-white rounded-xl p-4 shadow-lg border border-gray-200">
      <div className="flex items-center justify-between mb-4">
        <div className="flex items-center gap-2">
          <div className="p-2 bg-purple-100 rounded-lg">
            <FileText className="w-6 h-6 text-purple-600" />
          </div>
          <h3 className="font-semibold text-gray-700">Generate Report</h3>
        </div>
        <div className="flex items-center gap-2 text-sm text-gray-500">
          <Calendar className="w-4 h-4" />
          {isMounted ? new Date().toLocaleDateString() : ''}
        </div>
      </div>
      
      <div className="space-y-3 mb-4">
        <div className="grid grid-cols-2 gap-3 text-sm">
          <div className="bg-gray-50 rounded-lg p-3">
            <div className="text-gray-500">Total Time</div>
            <div className="text-lg font-bold text-gray-900">{statistics.totalTime.toFixed(1)}s</div>
          </div>
          <div className="bg-gray-50 rounded-lg p-3">
            <div className="text-gray-500">Energy Generated</div>
            <div className="text-lg font-bold text-gray-900">{(statistics.totalEnergyGenerated / 1000).toFixed(1)} kJ</div>
          </div>
          <div className="bg-gray-50 rounded-lg p-3">
            <div className="text-gray-500">Total Impacts</div>
            <div className="text-lg font-bold text-gray-900">{statistics.totalImpacts}</div>
          </div>
          <div className="bg-gray-50 rounded-lg p-3">
            <div className="text-gray-500">Max Compaction</div>
            <div className="text-lg font-bold text-gray-900">{statistics.maxSoilCompaction.toFixed(1)}%</div>
          </div>
        </div>
      </div>
      
      <button
        onClick={generatePDFReport}
        className="w-full flex items-center justify-center gap-2 bg-purple-600 hover:bg-purple-700 text-white py-3 px-4 rounded-lg font-medium transition-colors"
      >
        <Download className="w-5 h-5" />
        Download Report
      </button>
    </div>
  );
}
